adobe/helix-simulator

- CONTRIBUTING.md
- src/HelixServer.js
PR for https://github.com/adobe/petridish/issues/13
> Log the error and return 500

- src/HelixProject.js
- src/HelixServer.js
- test/hlx_project_test.js
- test/specs/emptycfg/helix-config.yaml
- test/specs/emptycfg/index.md
- test/specs/emptycfg/src/html.htl
> helix-config.yaml with no values produces error

- examples/soupdemo/package.json
> chore(package): update @adobe/helix-cli to version 0.2.2

- src/HelixServer.js
- src/RequestContext.js
- test/hlx_server_test.js
- test/specs/expected_dump.html
- test/specs/local/.hlx/build/dump_html.js
> Request object from payload is not complete 

- .circleci/config.yml
- package-lock.json
- package.json
> Use new release management rules 

- src/HelixServer.js
- test/specs/expected_dump.html
PR for https://github.com/adobe/petridish/issues/41
I have some doubt because of the comment which was there before... I could not find a case where there are 2 slashes...
> Path property from payload does not start with a `/`

- src/GitUrl.js
- src/HelixProject.js
- test/hlx_project_test.js
> hlx up cannot be used offline

- src/HelixServer.js
- src/RequestContext.js
- test/hlx_server_test.js
- test/specs/expected_dump.html
- test/specs/local/.hlx/build/dump_html.js
- test/utils_test.js
> Introduce params and new req parameter

- package-lock.json
- package.json
- src/HelixServer.js
- test/specs/expected_dump.html
> Align with openwhisk

- package-lock.json
- package.json
- src/HelixProject.js
- test/hlx_project_test.js
- test/specs/emptycfg/helix-config.yaml
- test/specs/remote/helix-config.yaml
> server doesn't use the Helix-Config but still relies on the parsed helix-config

- package-lock.json
- src/HelixServer.js
Needed for adobe/hypermedia-pipeline#97
> Enable remote ESI includes

- CONTRIBUTING.md
- correct project name
- removing internal adobe links
- removing link to non-existent pull request template
> 📝 contributing.md updates

- .npmignore
> strip unnecessary weight from published npm package #113

- .vscode/launch.json
- package-lock.json
- package.json
- src/utils.js
- test/hlx_server_test.js
> [Regression] Request to content assets files no longer work #116

- package-lock.json
- src/HelixProject.js
- src/HelixServer.js
- src/RequestContext.js
- src/utils.js
- test/hlx_project_test.js
- test/hlx_server_test.js
- test/hlx_strain_select_test.js
- test/specs/expected_index.html
- test/specs/expected_index.json
- test/specs/expected_index_dev.html
- test/specs/expected_index_dev.json
- test/specs/local/build/html.js
- test/specs/local/build/json.js
- test/specs/local/helix-config.yaml
- test/specs/local/readme.md
- test/specs/strain-select-test.yaml
- test/template_resolver_tests.js
- test/utils_test.js
fixes #126, fixes #127, fixes #128, fixes #110, fixes #105
> Select strain based on request variables

- src/HelixServer.js
- src/utils.js
- test/hlx_server_test.js
- test/specs/expected_proxy_docs.json
- test/specs/proxy/build/html.js
- test/specs/proxy/helix-config.yaml
- test/specs/proxy/index.md
- test/specs/proxy/src/html.htl
> support for proxy strains #133

- src/HelixServer.js
> Pass mount root as `rootPath` params #137

- src/HelixServer.js
- src/utils.js
- test/hlx_server_test.js
- test/utils_test.js
> helix up should check port 3000 being occupied #139

- .circleci/config.yml
- .gitignore
- CONTRIBUTING.md
- package-lock.json
- package.json
> build(config): Use semantic-release

- .circleci/config.yml
PR for https://github.com/adobe/helix-continuous/issues/9
> Smoke test workflow sporadically fails while smoke tests were successful

- src/HelixServer.js
- test/hlx_server_test.js
- test/specs/expected_esi.html
- test/specs/expected_recesi.html
- test/specs/local/build/esi1_html.js
- test/specs/local/build/esi2_html.js
- test/specs/local/build/esi3_html.js
- test/specs/local/build/esi_html.js
- test/specs/local/hello.txt
fix #162
(still need to add tests)
> fix(server): use request-promise as ESI http client to fix resursive ESI

- .releaserc.js
- package.json
> chore(release): semantic-release now updates the package.json

- package-lock.json
- package.json
- test/template_resolver_tests.js
- test/utils_test.js
Reverts adobe/helix-simulator#172
> Revert "Update @adobe/helix-shared to the latest version 🚀"

- src/GitManager.js
- src/HelixProject.js
- src/HelixServer.js
- src/RequestContext.js
- src/utils.js
- test/hlx_project_test.js
- test/hlx_server_test.js
- test/specs/api_repo/README.md
- test/specs/api_repo/htdocs/welcome.txt
- test/specs/expected_api_welcome.txt
- test/specs/expected_index.html
- test/specs/expected_index2.html
- test/specs/expected_index_dev.html
- test/specs/invalid_no_git/helix-config.yaml
- test/specs/local/build/html.js
- test/specs/local/helix-config.yaml
> fix(server): Add option to map giturls to local git repositories

- src/GitManager.js
- src/HelixServer.js
- src/RequestContext.js
- test/hlx_server_test.js
- test/specs/api_repo/docs/introduction.md
- test/specs/expected_api_introduction.html
- test/specs/expected_index_docs.json
- test/specs/local/helix-config.yaml
- test/utils_test.js
> fix(server): Content URL remapping doesn't work

- src/HelixServer.js
- src/RequestContext.js
- test/hlx_server_test.js
- test/specs/expected_index_post.html
- test/specs/local/build/post_html.js
- test/utils_test.js
> feat(server): process post request body

- src/RequestContext.js
- test/utils_test.js
> fix(server): add x-old-url and x-repo-root-path to __ow_headers

- src/HelixProject.js
- test/hlx_server_test.js
- test/specs/expected_index3.html
- test/specs/local/build/helper.js
- test/specs/local/build/helper2.js
- test/specs/local/build/html.js
- test/specs/local/src/module.js
- test/specs/local/src/module2.js
> fix(project): ensure modules in 'src' are also invalidated

- src/utils.js
- test/hlx_server_test.js
- test/specs/expected_proxy_docs_chroot.html
> fix(proxy): use original request path when processing proxy strains

- src/HelixProject.js
- src/HelixServer.js
- test/hlx_project_test.js
> Add src directory and make banner optional

- package.json
- src/HelixProject.js
- src/HelixServer.js
- test/hlx_strain_select_test.js
> fix(server): honor x-strain cookie

- .circleci/config.yml
Many test failures, potentially related to `helix-simulator`
> CircleCI Setup for Windows (failing)

- package-lock.json
- package.json
- test/hlx_server_test.js
- test/specs/expected_esiremove1.html
- test/specs/expected_esiremove2.html
- test/specs/local/build/esiremove1_html.js
- test/specs/local/build/esiremove2_html.js
Greenkeeper does not find it. Strange.
> chore(package): nodesi update to 1.12.1

- src/HelixProject.js
- src/TemplateResolver.js
- test/hlx_server_test.js
- test/specs/expected_cgi.txt
- test/specs/local/build/cgi-bin/post.info.json
- test/specs/local/build/cgi-bin/post.js
> feat(server): add support for cgi-bin

- src/HelixServer.js
- src/RequestContext.js
- test/hlx_server_test.js
- test/specs/expected_docs_index.html
- test/specs/local/docs/index.md
- test/utils_test.js
> feat(server): redirect for directory requests without trailing slash

- package-lock.json
- package.json
- src/utils.js
- test/hlx_server_test.js
> feat(server): use GITHUB_TOKEN when available to fetch static content

- src/HelixProject.js
- src/HelixServer.js
- test/hlx_project_test.js
> fix(server): modules required from src fail loading

- .circleci/config.yml
> fix(ci): update to node 10

- .circleci/config.yml
- .gitignore
- package-lock.json
- package.json
- src/GitManager.js
- src/HelixProject.js
- src/HelixServer.js
- test/hlx_project_test.js
- test/hlx_server_test.js
> feat(log): use helix-log

- src/HelixServer.js
- test/hlx_server_test.js
> fix(server): add support for azure blobs

- src/HelixServer.js
- test/hlx_server_test.js
Please ensure your pull request adheres to the following guidelines:
#384 
Thanks for contributing!
> fix(server): add support for fonts redirects (#384)

- 1
- package-lock.json
- package.json
- src/HelixProject.js
- src/HelixServer.js
- test/hlx_server_test.js
- test/specs/local/helix-index.yaml
Please ensure your pull request adheres to the following guidelines:
#385 
Thanks for contributing!
> feat(HelixServer): Implement Aloglia Proxy similar to VCL (#385)

- src/HelixServer.js
- test/hlx_server_test.js
…de redirects (#387)
Please ensure your pull request adheres to the following guidelines:
#387 
Thanks for contributing!
> fix(HelixServer): server-side reverse proxies instead of client-side redirects (#387)

- src/RequestContext.js
- test/template_resolver_tests.js
- test/utils_test.js
> feat(request): support for X-CDN-URL header

- package-lock.json
- package.json
- src/GitManager.js
- src/HelixProject.js
- src/HelixServer.js
- src/LiveReload.js
- src/RequestContext.js
- src/utils.js
- test/hlx_livereload_test.js
- test/hlx_server_test.js
- test/specs/expected_index_w_lr.html
- test/specs/expected_index_w_lr_nobody.html
- test/specs/expected_index_w_lr_nohead.html
- test/specs/expected_index_w_lr_nohtml.html
- test/specs/expected_recesi_w_lr.html
- test/specs/local/build/head_html.info.json
- test/specs/local/build/head_html.js
- test/specs/local/build/nobody_html.info.json
- test/specs/local/build/nobody_html.js
- test/specs/local/build/nohead_html.info.json
- test/specs/local/build/nohead_html.js
- test/specs/local/build/nohtml_html.info.json
- test/specs/local/build/nohtml_html.js
- test/specs/local/htdocs/dist/styles1.css
- test/utils.js
> feat: implement live-reload

- src/utils.js
- test/hlx_server_test.js
> fix(server): serve images from hlx_

- src/HelixServer.js
- test/hlx_server_test.js
> feat(sim): proxy all hlx_ and _query requests to inner cdn

- src/utils.js
- test/hlx_server_test.js
> fix(content): use content proxy v2

- src/utils.js
> fix(proxy): fix hanging requests to fastly

- src/HelixServer.js
- test/hlx_server_test.js
> fix(fonts): use full path to fetch fonts

- src/RequestContext.js
> fix(server): clone of request object fails with node 15.x

- package-lock.json
- src/HelixProject.js
- src/HelixServer.js
- src/RequestContext.js
- src/utils.js
- test/hlx_server_test.js
- test/specs/pagesproxy/index.html
> feat(server): add permanent proxy mode

- src/utils.js
- test/hlx_server_test.js
> feat(proxy): dump response with loglevel silly

- src/HelixServer.js
- test/hlx_server_test.js
> fix(server): use correct ref/repo/owner for locally mouted github

- src/HelixServer.js
- src/utils.js
- test/utils_test.js
> fix(proxy): strip query params from proxy reqests

- src/GitManager.js
- src/GitMapping.js
- src/HelixServer.js
- src/utils.js
- test/hlx_server_test.js
> Good git server names

- package-lock.json
- src/utils.js
> fix(proxy): remove content-endoding

- src/utils.js
> fix(proxy): remove content-encoding in all cases

- package-lock.json
- src/utils.js
> fix: use debug log level for 3xx responses from proxy
